const initial_values = {
  primary_principal: {
    first_name: "",
    last_name: "",
    title: "",
    principal_percentage_ownership: "",
    principal_dob_month: "",
    principal_dob_day: "",
    principal_dob_year: "",
    principal_tax_id: "",
    principal_address_line1: "",
    principal_address_line2: "",
    principal_address_city: "",
    principal_address_region: "",
    principal_address_zip: "",
    email: "",
    principal_phone:""
  },
  principal_2: {
    first_name: "",
    last_name: "",
    title: "",
    principal_percentage_ownership: "",
    principal_dob_month: "",
    principal_dob_day: "",
    principal_dob_year: "",
    principal_tax_id: "",
    principal_address_line1: "",
    principal_address_line2: "",
    principal_address_city: "",
    principal_address_region: "",
    principal_address_zip: "",
    email: "",
    principal_phone:""
  },
  principal_3: {
    first_name: "",
    last_name: "",
    title: "",
    principal_percentage_ownership: "",
    principal_dob_month: "",
    principal_dob_day: "",
    principal_dob_year: "",
    principal_tax_id: "",
    principal_address_line1: "",
    principal_address_line2: "",
    principal_address_city: "",
    principal_address_region: "",
    principal_address_zip: "",
    email: "",
    principal_phone:""
  },
  principal_4: {
    first_name: "",
    last_name: "",
    title: "",
    principal_percentage_ownership: "",
    principal_dob_month: "",
    principal_dob_day: "",
    principal_dob_year: "",
    principal_tax_id: "",
    principal_address_line1: "",
    principal_address_line2: "",
    principal_address_city: "",
    principal_address_region: "",
    principal_address_zip: "",
    email: "",
    principal_phone:""
  },
};

export default initial_values;
