const initial_values = {
annual_ach_volume: "1000000",
annual_card_volume: "100000",
average_ach_transfer_amount: "100000",
average_card_transfer_amount: "5000",
bank_account_name: "Hollywood Bicycles, LLC",
bank_account_number: "123456789",
bank_routing_number: "123456789",
business_address_city: "Los Angeles",
business_address_line1: "123 Main Street",
business_address_line2: "Suite 1",
business_address_postal_code: "90650",
business_address_region: "CA",
business_description: "Local Bike shop specializing in road bike sales and repairs.",
business_incorporation_day: "01",
business_incorporation_month: "5",
business_incorporation_year: "1993",
business_name: "Hollywood Bicycles, LLC",
business_phone: "123-456-7899",
business_tax_id: "123456789",
business_to_business_volume_percentage: "0",
business_to_consumer_volume_percentage: "100",
business_type: "CORPORATION",
processed_payments_before:"true", 
card_present_percentage: "0",
consumer_to_consumer_volume_percentage: "0",
credit_check_allowed: null,
default_statement_descriptor: "Hollywood Bikes",
doing_business_as: "Hollywood Bicycles, LLC",
ecommerce_percentage: "100",
mail_order_telephone_order_percentage: "0",
max_transaction_amount: "5000",
merchant_agreement_acceptance: null,
other_volume_percentage: "0",
ownership_type: "PRIVATE",
person_to_person_volume_percentage: "0",
refund_policy: "NO_REFUNDS",
website: "www.hollywoodbicycles.io",
  primary_principal: {
    first_name: "Alex",
    last_name: "Smith",
    title: "CEO",
    principal_percentage_ownership: "100",
    principal_dob_day: "01",
    principal_dob_month: "1",    
    principal_dob_year: "1990",
    principal_tax_id: "123456789",
    principal_address_line1: "123 Home Ave",
    principal_address_line2: "Apt 1",
    principal_address_city: "Los Angeles",
    principal_address_region: "CA",
    principal_address_zip: "90650",
    email: "alex.smith@hollywoodbicycles.com",
    principal_phone:"1234567"
  },
  principal_2: {
    first_name: "",
    last_name: "",
    title: "",
    principal_percentage_ownership: "",
    principal_dob_month: "",
    principal_dob_day: "",
    principal_dob_year: "",
    principal_tax_id: "",
    principal_address_line1: "",
    principal_address_line2: "",
    principal_address_city: "",
    principal_address_region: "",
    principal_address_zip: "",
    email: "",
    principal_phone:""
  },
  principal_3: {
    first_name: "",
    last_name: "",
    title: "",
    principal_percentage_ownership: "",
    principal_dob_month: "",
    principal_dob_day: "",
    principal_dob_year: "",
    principal_tax_id: "",
    principal_address_line1: "",
    principal_address_line2: "",
    principal_address_city: "",
    principal_address_region: "",
    principal_address_zip: "",
    email: "",
    principal_phone:""
  },
  principal_4: {
    first_name: "",
    last_name: "",
    title: "",
    principal_percentage_ownership: "",
    principal_dob_month: "",
    principal_dob_day: "",
    principal_dob_year: "",
    principal_tax_id: "",
    principal_address_line1: "",
    principal_address_line2: "",
    principal_address_city: "",
    principal_address_region: "",
    principal_address_zip: "",
    email: "",
    principal_phone:""
  },
};

export default initial_values;
